<a href="https://colab.research.google.com/github/PattipatiSaiPrasanna123/python-mini-projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#Numpy-Numeric python
# most powerful package-library
# Numpy-dimemsions
#A-one dimension array
#[A,B]||[A
        #B]-Two dimensional Array-row||column
#Three Dimensional
#Array -staring,manipulating,similar Data type
#Faster than any mathematical function A
#memory efficiency
#support multi dimensional arrays
#speed(Numpy operations)>speed(Lists operations)

In [ ]:
#install numpy - pip3 install numpy//pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr1D = np.array([1,2,3,4,5] )
print(arr1D)

[1 2 3 4 5]


In [ ]:
arr2D = np.array([
     [1,2,3],[4,5,6]
])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
allZeros = np.zeros((2,3))
print(allZeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
allOnes = np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
allConstant = np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:

#Identity Matrix -Aii = 1 && Aij = 0
#For all A belongs to R MxN
#Aij -

In [ ]:
rand1 = np.random.rand(3,3)
print(rand1)

[[0.84628724 0.10772356 0.01769269]
 [0.56550001 0.77760029 0.22824899]
 [0.53788332 0.25546695 0.35193369]]


In [ ]:
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[18 19 17]
 [13 11 19]
 [11 16 15]]


In [ ]:

# Array properties
arr=np.array(([1,2,3,4],[2,3,4,5]))
print(arr)
# Shape of the array
print(f'The shape of the array is {arr.shape}')
# Size of array
print(f'The size of the array is {arr.size}')
#Datatype of array
print(f'The Data type of the array is {arr.dtype}')
#Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [ ]:

# Indexing and Slicing

# Access the elements in 1D Array

arr =np.array([1,2,3,4])
print(arr)
print(arr[3])

# Slicing the elements
print(arr[0:3])

# Access the elements in 2D Array
arr2 = np.array(([1,2,3],[2,3,4]))
print(arr2)
print(arr2[1,1])
print(arr2[0,:])#first row with all Column
print(arr2[:,0])#first column with all rows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
l1 = np.arange(0,10,2)
print(l1)

[0 2 4 6 8]


In [ ]:
a = np.array([1,2,3])
b = np.array ([3,4,5])
print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
b1 = np.array([[1,2,3], [2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [ ]:
b1
b2

array([[5, 6],
       [7, 8],
       [1, 3]])

In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
